name: burgernook
description: A new Flutter application.
version: 1.0.0+3

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  shared_preferences: ^0.5.6+1
  share: ^0.6.3+5
  http: ^0.12.0+4
  connectivity: ^0.4.5+3
  location: ^2.3.5
  geocoder: ^0.2.1
  carousel_slider: ^1.4.1
  provider: ^4.0.2
  image_picker: ^0.6.3+1
  path_provider: ^1.6.0
  image: ^2.1.4
  markdown:
  photo_view: ^0.9.2
  url_launcher: ^5.4.2

  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  assets:
    - assets/
    - lang/
  fonts:
    - family: NimbusSansT_BlackCondensed
      fonts:
        - asset: assets/font/NimbusSansT-BlackCondensed.otf
    - family: GE_Dinar_One_Light
      fonts:
        - asset: assets/font/GE_Dinar_One_Light.otf
    - family: GE_Dinar_One_Medium
      fonts:
        - asset: assets/font/GE-Dinar-One-Medium.otf
    - family: arlrdbd
      fonts:
        - asset: assets/font/arlrdbd.ttf